package ycl.protobean;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WA_YCL_TEST_0001.proto

public final class WA_YCL_TEST_0001_PROTO {
  private WA_YCL_TEST_0001_PROTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PB_WA_YCL_TEST_0001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:PB_WA_YCL_TEST_0001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *name="QQ"     rmk=""  val="QQ号码"
     * </pre>
     *
     * <code>string B000001 = 1;</code>
     */
    String getB000001();
    /**
     * <pre>
     *name="QQ"     rmk=""  val="QQ号码"
     * </pre>
     *
     * <code>string B000001 = 1;</code>
     */
    com.google.protobuf.ByteString
        getB000001Bytes();

    /**
     * <pre>
     *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
     * </pre>
     *
     * <code>string B000002 = 2;</code>
     */
    String getB000002();
    /**
     * <pre>
     *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
     * </pre>
     *
     * <code>string B000002 = 2;</code>
     */
    com.google.protobuf.ByteString
        getB000002Bytes();

    /**
     * <pre>
     *name="ZWM"    rmk=""  val="中文名"
     * </pre>
     *
     * <code>string B000003 = 3;</code>
     */
    String getB000003();
    /**
     * <pre>
     *name="ZWM"    rmk=""  val="中文名"
     * </pre>
     *
     * <code>string B000003 = 3;</code>
     */
    com.google.protobuf.ByteString
        getB000003Bytes();

    /**
     * <pre>
     *name="JZD"    rmk=""  val="居住地"
     * </pre>
     *
     * <code>string B000004 = 4;</code>
     */
    String getB000004();
    /**
     * <pre>
     *name="JZD"    rmk=""  val="居住地"
     * </pre>
     *
     * <code>string B000004 = 4;</code>
     */
    com.google.protobuf.ByteString
        getB000004Bytes();

    /**
     * <pre>
     *name="XX"     rmk=""  val="学校"
     * </pre>
     *
     * <code>string B000005 = 5;</code>
     */
    String getB000005();
    /**
     * <pre>
     *name="XX"     rmk=""  val="学校"
     * </pre>
     *
     * <code>string B000005 = 5;</code>
     */
    com.google.protobuf.ByteString
        getB000005Bytes();

    /**
     * <pre>
     *name="JX"     rmk=""  val="家乡"
     * </pre>
     *
     * <code>string B000006 = 6;</code>
     */
    String getB000006();
    /**
     * <pre>
     *name="JX"     rmk=""  val="家乡"
     * </pre>
     *
     * <code>string B000006 = 6;</code>
     */
    com.google.protobuf.ByteString
        getB000006Bytes();

    /**
     * <pre>
     *name="CSRQ"   rmk=""  val="出生日期"
     * </pre>
     *
     * <code>string B000007 = 7;</code>
     */
    String getB000007();
    /**
     * <pre>
     *name="CSRQ"   rmk=""  val="出生日期"
     * </pre>
     *
     * <code>string B000007 = 7;</code>
     */
    com.google.protobuf.ByteString
        getB000007Bytes();

    /**
     * <pre>
     *name="XB"     rmk=""  val="性别"
     * </pre>
     *
     * <code>string B000008 = 8;</code>
     */
    String getB000008();
    /**
     * <pre>
     *name="XB"     rmk=""  val="性别"
     * </pre>
     *
     * <code>string B000008 = 8;</code>
     */
    com.google.protobuf.ByteString
        getB000008Bytes();
  }
  /**
   * Protobuf type {@code PB_WA_YCL_TEST_0001}
   */
  public  static final class PB_WA_YCL_TEST_0001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PB_WA_YCL_TEST_0001)
      PB_WA_YCL_TEST_0001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PB_WA_YCL_TEST_0001.newBuilder() to construct.
    private PB_WA_YCL_TEST_0001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PB_WA_YCL_TEST_0001() {
      b000001_ = "";
      b000002_ = "";
      b000003_ = "";
      b000004_ = "";
      b000005_ = "";
      b000006_ = "";
      b000007_ = "";
      b000008_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PB_WA_YCL_TEST_0001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              b000001_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              b000002_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              b000003_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              b000004_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              b000005_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              b000006_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              b000007_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              b000008_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WA_YCL_TEST_0001_PROTO.internal_static_PB_WA_YCL_TEST_0001_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WA_YCL_TEST_0001_PROTO.internal_static_PB_WA_YCL_TEST_0001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PB_WA_YCL_TEST_0001.class, Builder.class);
    }

    public static final int B000001_FIELD_NUMBER = 1;
    private volatile Object b000001_;
    /**
     * <pre>
     *name="QQ"     rmk=""  val="QQ号码"
     * </pre>
     *
     * <code>string B000001 = 1;</code>
     */
    public String getB000001() {
      Object ref = b000001_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000001_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="QQ"     rmk=""  val="QQ号码"
     * </pre>
     *
     * <code>string B000001 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getB000001Bytes() {
      Object ref = b000001_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000001_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000002_FIELD_NUMBER = 2;
    private volatile Object b000002_;
    /**
     * <pre>
     *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
     * </pre>
     *
     * <code>string B000002 = 2;</code>
     */
    public String getB000002() {
      Object ref = b000002_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000002_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
     * </pre>
     *
     * <code>string B000002 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getB000002Bytes() {
      Object ref = b000002_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000002_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000003_FIELD_NUMBER = 3;
    private volatile Object b000003_;
    /**
     * <pre>
     *name="ZWM"    rmk=""  val="中文名"
     * </pre>
     *
     * <code>string B000003 = 3;</code>
     */
    public String getB000003() {
      Object ref = b000003_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000003_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="ZWM"    rmk=""  val="中文名"
     * </pre>
     *
     * <code>string B000003 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getB000003Bytes() {
      Object ref = b000003_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000003_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000004_FIELD_NUMBER = 4;
    private volatile Object b000004_;
    /**
     * <pre>
     *name="JZD"    rmk=""  val="居住地"
     * </pre>
     *
     * <code>string B000004 = 4;</code>
     */
    public String getB000004() {
      Object ref = b000004_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000004_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="JZD"    rmk=""  val="居住地"
     * </pre>
     *
     * <code>string B000004 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getB000004Bytes() {
      Object ref = b000004_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000004_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000005_FIELD_NUMBER = 5;
    private volatile Object b000005_;
    /**
     * <pre>
     *name="XX"     rmk=""  val="学校"
     * </pre>
     *
     * <code>string B000005 = 5;</code>
     */
    public String getB000005() {
      Object ref = b000005_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000005_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="XX"     rmk=""  val="学校"
     * </pre>
     *
     * <code>string B000005 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getB000005Bytes() {
      Object ref = b000005_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000005_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000006_FIELD_NUMBER = 6;
    private volatile Object b000006_;
    /**
     * <pre>
     *name="JX"     rmk=""  val="家乡"
     * </pre>
     *
     * <code>string B000006 = 6;</code>
     */
    public String getB000006() {
      Object ref = b000006_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000006_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="JX"     rmk=""  val="家乡"
     * </pre>
     *
     * <code>string B000006 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getB000006Bytes() {
      Object ref = b000006_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000006_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000007_FIELD_NUMBER = 7;
    private volatile Object b000007_;
    /**
     * <pre>
     *name="CSRQ"   rmk=""  val="出生日期"
     * </pre>
     *
     * <code>string B000007 = 7;</code>
     */
    public String getB000007() {
      Object ref = b000007_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000007_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="CSRQ"   rmk=""  val="出生日期"
     * </pre>
     *
     * <code>string B000007 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getB000007Bytes() {
      Object ref = b000007_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000007_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B000008_FIELD_NUMBER = 8;
    private volatile Object b000008_;
    /**
     * <pre>
     *name="XB"     rmk=""  val="性别"
     * </pre>
     *
     * <code>string B000008 = 8;</code>
     */
    public String getB000008() {
      Object ref = b000008_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        b000008_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *name="XB"     rmk=""  val="性别"
     * </pre>
     *
     * <code>string B000008 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getB000008Bytes() {
      Object ref = b000008_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        b000008_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getB000001Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, b000001_);
      }
      if (!getB000002Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, b000002_);
      }
      if (!getB000003Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, b000003_);
      }
      if (!getB000004Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, b000004_);
      }
      if (!getB000005Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, b000005_);
      }
      if (!getB000006Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, b000006_);
      }
      if (!getB000007Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, b000007_);
      }
      if (!getB000008Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, b000008_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getB000001Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, b000001_);
      }
      if (!getB000002Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, b000002_);
      }
      if (!getB000003Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, b000003_);
      }
      if (!getB000004Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, b000004_);
      }
      if (!getB000005Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, b000005_);
      }
      if (!getB000006Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, b000006_);
      }
      if (!getB000007Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, b000007_);
      }
      if (!getB000008Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, b000008_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PB_WA_YCL_TEST_0001)) {
        return super.equals(obj);
      }
      PB_WA_YCL_TEST_0001 other = (PB_WA_YCL_TEST_0001) obj;

      boolean result = true;
      result = result && getB000001()
          .equals(other.getB000001());
      result = result && getB000002()
          .equals(other.getB000002());
      result = result && getB000003()
          .equals(other.getB000003());
      result = result && getB000004()
          .equals(other.getB000004());
      result = result && getB000005()
          .equals(other.getB000005());
      result = result && getB000006()
          .equals(other.getB000006());
      result = result && getB000007()
          .equals(other.getB000007());
      result = result && getB000008()
          .equals(other.getB000008());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + B000001_FIELD_NUMBER;
      hash = (53 * hash) + getB000001().hashCode();
      hash = (37 * hash) + B000002_FIELD_NUMBER;
      hash = (53 * hash) + getB000002().hashCode();
      hash = (37 * hash) + B000003_FIELD_NUMBER;
      hash = (53 * hash) + getB000003().hashCode();
      hash = (37 * hash) + B000004_FIELD_NUMBER;
      hash = (53 * hash) + getB000004().hashCode();
      hash = (37 * hash) + B000005_FIELD_NUMBER;
      hash = (53 * hash) + getB000005().hashCode();
      hash = (37 * hash) + B000006_FIELD_NUMBER;
      hash = (53 * hash) + getB000006().hashCode();
      hash = (37 * hash) + B000007_FIELD_NUMBER;
      hash = (53 * hash) + getB000007().hashCode();
      hash = (37 * hash) + B000008_FIELD_NUMBER;
      hash = (53 * hash) + getB000008().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PB_WA_YCL_TEST_0001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PB_WA_YCL_TEST_0001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PB_WA_YCL_TEST_0001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PB_WA_YCL_TEST_0001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PB_WA_YCL_TEST_0001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PB_WA_YCL_TEST_0001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PB_WA_YCL_TEST_0001)
        PB_WA_YCL_TEST_0001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WA_YCL_TEST_0001_PROTO.internal_static_PB_WA_YCL_TEST_0001_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WA_YCL_TEST_0001_PROTO.internal_static_PB_WA_YCL_TEST_0001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PB_WA_YCL_TEST_0001.class, Builder.class);
      }

      // Construct using WA_YCL_TEST_0001_PROTO.PB_WA_YCL_TEST_0001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        b000001_ = "";

        b000002_ = "";

        b000003_ = "";

        b000004_ = "";

        b000005_ = "";

        b000006_ = "";

        b000007_ = "";

        b000008_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WA_YCL_TEST_0001_PROTO.internal_static_PB_WA_YCL_TEST_0001_descriptor;
      }

      @Override
      public PB_WA_YCL_TEST_0001 getDefaultInstanceForType() {
        return PB_WA_YCL_TEST_0001.getDefaultInstance();
      }

      @Override
      public PB_WA_YCL_TEST_0001 build() {
        PB_WA_YCL_TEST_0001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PB_WA_YCL_TEST_0001 buildPartial() {
        PB_WA_YCL_TEST_0001 result = new PB_WA_YCL_TEST_0001(this);
        result.b000001_ = b000001_;
        result.b000002_ = b000002_;
        result.b000003_ = b000003_;
        result.b000004_ = b000004_;
        result.b000005_ = b000005_;
        result.b000006_ = b000006_;
        result.b000007_ = b000007_;
        result.b000008_ = b000008_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PB_WA_YCL_TEST_0001) {
          return mergeFrom((PB_WA_YCL_TEST_0001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PB_WA_YCL_TEST_0001 other) {
        if (other == PB_WA_YCL_TEST_0001.getDefaultInstance()) return this;
        if (!other.getB000001().isEmpty()) {
          b000001_ = other.b000001_;
          onChanged();
        }
        if (!other.getB000002().isEmpty()) {
          b000002_ = other.b000002_;
          onChanged();
        }
        if (!other.getB000003().isEmpty()) {
          b000003_ = other.b000003_;
          onChanged();
        }
        if (!other.getB000004().isEmpty()) {
          b000004_ = other.b000004_;
          onChanged();
        }
        if (!other.getB000005().isEmpty()) {
          b000005_ = other.b000005_;
          onChanged();
        }
        if (!other.getB000006().isEmpty()) {
          b000006_ = other.b000006_;
          onChanged();
        }
        if (!other.getB000007().isEmpty()) {
          b000007_ = other.b000007_;
          onChanged();
        }
        if (!other.getB000008().isEmpty()) {
          b000008_ = other.b000008_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PB_WA_YCL_TEST_0001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PB_WA_YCL_TEST_0001) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object b000001_ = "";
      /**
       * <pre>
       *name="QQ"     rmk=""  val="QQ号码"
       * </pre>
       *
       * <code>string B000001 = 1;</code>
       */
      public String getB000001() {
        Object ref = b000001_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000001_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="QQ"     rmk=""  val="QQ号码"
       * </pre>
       *
       * <code>string B000001 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getB000001Bytes() {
        Object ref = b000001_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000001_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="QQ"     rmk=""  val="QQ号码"
       * </pre>
       *
       * <code>string B000001 = 1;</code>
       */
      public Builder setB000001(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000001_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="QQ"     rmk=""  val="QQ号码"
       * </pre>
       *
       * <code>string B000001 = 1;</code>
       */
      public Builder clearB000001() {
        
        b000001_ = getDefaultInstance().getB000001();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="QQ"     rmk=""  val="QQ号码"
       * </pre>
       *
       * <code>string B000001 = 1;</code>
       */
      public Builder setB000001Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000001_ = value;
        onChanged();
        return this;
      }

      private Object b000002_ = "";
      /**
       * <pre>
       *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
       * </pre>
       *
       * <code>string B000002 = 2;</code>
       */
      public String getB000002() {
        Object ref = b000002_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000002_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
       * </pre>
       *
       * <code>string B000002 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getB000002Bytes() {
        Object ref = b000002_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000002_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
       * </pre>
       *
       * <code>string B000002 = 2;</code>
       */
      public Builder setB000002(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000002_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
       * </pre>
       *
       * <code>string B000002 = 2;</code>
       */
      public Builder clearB000002() {
        
        b000002_ = getDefaultInstance().getB000002();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="RSQQ"   rmk=""  val="可能认识人的QQ号码"
       * </pre>
       *
       * <code>string B000002 = 2;</code>
       */
      public Builder setB000002Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000002_ = value;
        onChanged();
        return this;
      }

      private Object b000003_ = "";
      /**
       * <pre>
       *name="ZWM"    rmk=""  val="中文名"
       * </pre>
       *
       * <code>string B000003 = 3;</code>
       */
      public String getB000003() {
        Object ref = b000003_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000003_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="ZWM"    rmk=""  val="中文名"
       * </pre>
       *
       * <code>string B000003 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getB000003Bytes() {
        Object ref = b000003_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000003_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="ZWM"    rmk=""  val="中文名"
       * </pre>
       *
       * <code>string B000003 = 3;</code>
       */
      public Builder setB000003(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000003_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="ZWM"    rmk=""  val="中文名"
       * </pre>
       *
       * <code>string B000003 = 3;</code>
       */
      public Builder clearB000003() {
        
        b000003_ = getDefaultInstance().getB000003();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="ZWM"    rmk=""  val="中文名"
       * </pre>
       *
       * <code>string B000003 = 3;</code>
       */
      public Builder setB000003Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000003_ = value;
        onChanged();
        return this;
      }

      private Object b000004_ = "";
      /**
       * <pre>
       *name="JZD"    rmk=""  val="居住地"
       * </pre>
       *
       * <code>string B000004 = 4;</code>
       */
      public String getB000004() {
        Object ref = b000004_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000004_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="JZD"    rmk=""  val="居住地"
       * </pre>
       *
       * <code>string B000004 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getB000004Bytes() {
        Object ref = b000004_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000004_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="JZD"    rmk=""  val="居住地"
       * </pre>
       *
       * <code>string B000004 = 4;</code>
       */
      public Builder setB000004(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000004_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="JZD"    rmk=""  val="居住地"
       * </pre>
       *
       * <code>string B000004 = 4;</code>
       */
      public Builder clearB000004() {
        
        b000004_ = getDefaultInstance().getB000004();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="JZD"    rmk=""  val="居住地"
       * </pre>
       *
       * <code>string B000004 = 4;</code>
       */
      public Builder setB000004Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000004_ = value;
        onChanged();
        return this;
      }

      private Object b000005_ = "";
      /**
       * <pre>
       *name="XX"     rmk=""  val="学校"
       * </pre>
       *
       * <code>string B000005 = 5;</code>
       */
      public String getB000005() {
        Object ref = b000005_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000005_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="XX"     rmk=""  val="学校"
       * </pre>
       *
       * <code>string B000005 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getB000005Bytes() {
        Object ref = b000005_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000005_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="XX"     rmk=""  val="学校"
       * </pre>
       *
       * <code>string B000005 = 5;</code>
       */
      public Builder setB000005(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000005_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="XX"     rmk=""  val="学校"
       * </pre>
       *
       * <code>string B000005 = 5;</code>
       */
      public Builder clearB000005() {
        
        b000005_ = getDefaultInstance().getB000005();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="XX"     rmk=""  val="学校"
       * </pre>
       *
       * <code>string B000005 = 5;</code>
       */
      public Builder setB000005Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000005_ = value;
        onChanged();
        return this;
      }

      private Object b000006_ = "";
      /**
       * <pre>
       *name="JX"     rmk=""  val="家乡"
       * </pre>
       *
       * <code>string B000006 = 6;</code>
       */
      public String getB000006() {
        Object ref = b000006_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000006_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="JX"     rmk=""  val="家乡"
       * </pre>
       *
       * <code>string B000006 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getB000006Bytes() {
        Object ref = b000006_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000006_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="JX"     rmk=""  val="家乡"
       * </pre>
       *
       * <code>string B000006 = 6;</code>
       */
      public Builder setB000006(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000006_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="JX"     rmk=""  val="家乡"
       * </pre>
       *
       * <code>string B000006 = 6;</code>
       */
      public Builder clearB000006() {
        
        b000006_ = getDefaultInstance().getB000006();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="JX"     rmk=""  val="家乡"
       * </pre>
       *
       * <code>string B000006 = 6;</code>
       */
      public Builder setB000006Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000006_ = value;
        onChanged();
        return this;
      }

      private Object b000007_ = "";
      /**
       * <pre>
       *name="CSRQ"   rmk=""  val="出生日期"
       * </pre>
       *
       * <code>string B000007 = 7;</code>
       */
      public String getB000007() {
        Object ref = b000007_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000007_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="CSRQ"   rmk=""  val="出生日期"
       * </pre>
       *
       * <code>string B000007 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getB000007Bytes() {
        Object ref = b000007_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000007_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="CSRQ"   rmk=""  val="出生日期"
       * </pre>
       *
       * <code>string B000007 = 7;</code>
       */
      public Builder setB000007(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000007_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="CSRQ"   rmk=""  val="出生日期"
       * </pre>
       *
       * <code>string B000007 = 7;</code>
       */
      public Builder clearB000007() {
        
        b000007_ = getDefaultInstance().getB000007();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="CSRQ"   rmk=""  val="出生日期"
       * </pre>
       *
       * <code>string B000007 = 7;</code>
       */
      public Builder setB000007Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000007_ = value;
        onChanged();
        return this;
      }

      private Object b000008_ = "";
      /**
       * <pre>
       *name="XB"     rmk=""  val="性别"
       * </pre>
       *
       * <code>string B000008 = 8;</code>
       */
      public String getB000008() {
        Object ref = b000008_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          b000008_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *name="XB"     rmk=""  val="性别"
       * </pre>
       *
       * <code>string B000008 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getB000008Bytes() {
        Object ref = b000008_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          b000008_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *name="XB"     rmk=""  val="性别"
       * </pre>
       *
       * <code>string B000008 = 8;</code>
       */
      public Builder setB000008(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b000008_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="XB"     rmk=""  val="性别"
       * </pre>
       *
       * <code>string B000008 = 8;</code>
       */
      public Builder clearB000008() {
        
        b000008_ = getDefaultInstance().getB000008();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *name="XB"     rmk=""  val="性别"
       * </pre>
       *
       * <code>string B000008 = 8;</code>
       */
      public Builder setB000008Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b000008_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PB_WA_YCL_TEST_0001)
    }

    // @@protoc_insertion_point(class_scope:PB_WA_YCL_TEST_0001)
    private static final PB_WA_YCL_TEST_0001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PB_WA_YCL_TEST_0001();
    }

    public static PB_WA_YCL_TEST_0001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PB_WA_YCL_TEST_0001>
        PARSER = new com.google.protobuf.AbstractParser<PB_WA_YCL_TEST_0001>() {
      @Override
      public PB_WA_YCL_TEST_0001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PB_WA_YCL_TEST_0001(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PB_WA_YCL_TEST_0001> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PB_WA_YCL_TEST_0001> getParserForType() {
      return PARSER;
    }

    @Override
    public PB_WA_YCL_TEST_0001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_WA_YCL_TEST_0001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PB_WA_YCL_TEST_0001_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026WA_YCL_TEST_0001.proto\"\235\001\n\023PB_WA_YCL_T" +
      "EST_0001\022\017\n\007B000001\030\001 \001(\t\022\017\n\007B000002\030\002 \001" +
      "(\t\022\017\n\007B000003\030\003 \001(\t\022\017\n\007B000004\030\004 \001(\t\022\017\n\007" +
      "B000005\030\005 \001(\t\022\017\n\007B000006\030\006 \001(\t\022\017\n\007B00000" +
      "7\030\007 \001(\t\022\017\n\007B000008\030\010 \001(\tB\030B\026WA_YCL_TEST_" +
      "0001_PROTOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PB_WA_YCL_TEST_0001_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PB_WA_YCL_TEST_0001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PB_WA_YCL_TEST_0001_descriptor,
        new String[] { "B000001", "B000002", "B000003", "B000004", "B000005", "B000006", "B000007", "B000008", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
